hirethemv2-main/hirethemv2/users/urls.py
from django.urls import path

from hirethemv2.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

hirethemv2-main/jobs/urls.py
from django.urls import path, include
from .views import job_list, detailed_job, create_job,create_company,update_job, delete_job, apply_job, show_student_list, download_student_list_csv, download_resumes


urlpatterns = [
    path("", view=job_list, name="jobs"),
    path("?=<int:pk>/", view=detailed_job, name="jobs-detail"),
    path("?=<int:pk>/update", view=update_job,name="updatejob"),
    path("createjob/", view=create_job, name="createjob"),
    path("createcompany/", view=create_company, name="createcompany"),
    path("<int:pk>/apply/", view=apply_job, name="apply-job"),
    path("<int:pk>/student-list/", view=show_student_list, name="show-student-list"),
    path('<int:job_id>/download_student_list_csv/', download_student_list_csv, name='download_student_list_csv'),
    path('<int:job_id>/download-resumes/', download_resumes, name='download_resumes'),
]

hirethemv2-main/hirethemv2/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from .validators import CustomUnicodeUsernameValidator

class User(AbstractUser):
    app_label = 'users'
    """
    Default custom user model for Hire-Them.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    class Department(models.TextChoices):
        CSE = "CSE", "COMPUTER SCIENCE"
        IT = "IT", "INFORMATION TECHNOLOGY"
        EE = "EE", "ELECTRIC ENGINEERING"
        CE = "CE", "CIVIL ENGINEERING"
        TE = "TE", "TEXTILE ENGINEERING"
        ME = "ME", "MECHANICAL ENGINEERING"
        OT = "OT", "OTHER"

    username_validator =  CustomUnicodeUsernameValidator()
    
    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 30 characters or fewer. Letters, digits, no spaces and ./_ character only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A user with that username already exists."),
        },
    )
    
    name = models.CharField(_("Name of User"), max_length=255)
    
    first_name = None  # type: ignore
    
    last_name = None  # type: ignore
    
    email = models.EmailField(max_length=100, unique=True)
    
    urn_number = models.CharField(
        max_length=16,
        unique=True,
        null=True,
        blank=True)

    phone_number = models.PositiveBigIntegerField(max_length=10, unique=True, blank=True, null=True)
    
    profile_picture = models.ImageField(
        upload_to="photos/profiles/",
        max_length=255,
        null=True,
        blank=True
    )

    bio = models.CharField(
        max_length=100,
        blank=True,
        null=True
    )
    
    department = models.CharField(
        max_length=5,
        choices=Department.choices,
        default=Department.CSE,
        blank=True,
        null=True,
    )

    address = models.CharField(
        max_length=500,
        blank=True,
        null=True,
        verbose_name="Your State and Country",
        help_text=(_("Enter your address in format - your state, your country"))
    )
    tenth_percentage = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    tenth_school_name = models.CharField(max_length=255, blank=True, null=True)
    twelth_percentage = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    twelth_school_name = models.CharField(max_length=255, blank=True, null=True)

    current_cgpa = models.DecimalField(max_digits=4, decimal_places=2, blank=True, null=True)
    active_backlogs = models.PositiveIntegerField(blank=True, null=True)

    
    # resume = models.FileField(
    #     upload_to="resumes/pdf/",
    #     blank=True,
    #     null=True,
    #     validators=[validate_file_extension],
    #     help_text=_(
    #         "Requires a ` pdf ` format of your resume."
    #     )
    # )
    
    github = models.CharField(
        max_length=500,
        blank=True,
        null=True,
        verbose_name="Github link",
        help_text=_(
            """

             - Requires a unique link of your github profile.<br>
             - Add link without 'https://'.

            """
        ),
        )

    REQUIRED_FIELDS = [
        "email",
        "name",
    ]

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

hirethemv2-main/hirethemv2/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

hirethemv2-main/hirethemv2/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()

class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"

user_detail_view = UserDetailView.as_view()

class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name", "urn_number", "profile_picture", "bio", "phone_number", "department", "address", "github",
              "tenth_percentage", "tenth_school_name", "twelth_percentage", "twelth_school_name",
               "current_cgpa", "active_backlogs"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user

user_update_view = UserUpdateView.as_view()

class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

user_redirect_view = UserRedirectView.as_view()

hirethemv2-main/hirethemv2/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<section style="background-color: #eee;">
  <div class="container py-5">
        <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
          <ol class="breadcrumb mb-0">
            <li class="breadcrumb-item" aria-current="page"><i class="fas fa-user-tie"></i> User Profile</li>
          </ol>
        </nav>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            {% if object.profile_picture %}
            <img src="{{object.profile_picture.url}}" alt="avatar"
              class="rounded-circle img-fluid" style="width: 150px;">
            {% else %}
            <img src="{% static 'images/defaults/profiles/default.jpg' %}" alt="avatar"
            class="rounded-circle img-fluid" style="width: 150px;">
            {% endif %}
            <h5 class="my-3 text-capitalize">{{object.name}}</h5>
            <p class="text-muted mb-3">{{object.bio}}</p>
            <div class="d-flex justify-content-center mb-2">
              {% if object.github %}
              <a class="btn btn-success" href="https://{{object.github}}" role="button"><i class="fa-brands fa-github"></i> Github Link</a>
              {% else %}
              <a class="btn btn-success disabled" role="button"><i class="fa-brands fa-github"></i> No Github Link</a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
              <li class="rounded-3 list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                <p class="mb-0">https://{{object.github}}</p>
              </li>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fa-regular fa-user" style="color: rgb(82, 53, 15);"></i> &nbsp;&nbsp;Full Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0 text-capitalize">{{object.name}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fa-solid fa-robot" style="color: #cd4df1;"></i> &nbsp;Username</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0" >{{object.username}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fa-solid fa-envelope"></i>&nbsp;&nbsp;&nbsp;Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{object.email}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fas fa-sort-numeric-up" style="color: #35b5be;"></i> &nbsp;URN</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{object.urn_number}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fas fa-school"></i> &nbsp;Current CGPA</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ object.current_cgpa|default_if_none:"Not provided" }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fas fa-school"></i> &nbsp;Active Backlogs</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ object.active_backlogs|default_if_none:"Not provided" }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fa-solid fa-phone" style="color: #1ccf1f;"></i> &nbsp;&nbsp;Mobile</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ object.phone_number|default_if_none:"Not provided" }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fa-solid fa-building" style="color: #1c8cb1;"></i> &nbsp;&nbsp;Department</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0 text-lowercase text-capitalize">{{object.get_department_display.lower}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fas fa-street-view" style="color: #b11c7d;"></i> &nbsp;Address</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{object.address|default_if_none:"Empty"}}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fas fa-percent"></i> &nbsp;10th Percentage</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ object.tenth_percentage|default_if_none:"Not provided" }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fas fa-school"></i> &nbsp;10th School Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ object.tenth_school_name|default_if_none:"Not provided" }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fas fa-percent"></i> &nbsp;12th Percentage</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ object.twelth_percentage|default_if_none:"Not provided" }}</p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0"><i class="fas fa-school"></i> &nbsp;12th School Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0">{{ object.twelth_school_name|default_if_none:"Not provided" }}</p>
              </div>
            </div>
            <hr>

          </div>
        </div>
        <div class="row">
          <div class="col">
            <div class="container">
              {% if object == request.user %}
              <!-- Action buttons -->
                <div class="col-sm-12 mb-5">
                  <a class="btn btn-primary" href="{% url 'users:update' %}" role="button"><i class="fas fa-user-circle"></i> Profile Update</a>
                  <a class="btn btn-primary" href="{% url 'account_email' %}" role="button"><i class="fas fa-envelope-open"></i> E-Mail Update</a>
                  <a class="btn btn-primary" href="{% url 'account_change_password' %}"><i class="fas fa-key"></i> Change Password</a>
                  <!-- Your Stuff: Custom user template urls -->
                </div>
              
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

hirethemv2-main/hirethemv2/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}